# Generated by Django 2.2.6 on 2019-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoImovel', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('kitnet', 'Kitnet')], default='', max_length=20)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='', max_length=8)),
                ('preco', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cep', models.CharField(default='', max_length=8)),
                ('endereco', models.CharField(default='', max_length=250)),
                ('tamanho', models.PositiveIntegerField()),
                ('quartos', models.PositiveSmallIntegerField()),
                ('andares', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_imovel')),
            ],
        ),
    ]
