# Generated by Django 2.2.6 on 2019-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_usuario'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='foto_usuario'),
        ),
    ]
