# Generated by Django 2.2.6 on 2019-10-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0002_auto_20191021_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='foto_imovel'),
        ),
    ]
