# Generated by Django 2.2.6 on 2019-10-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0003_auto_20191021_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
