# Generated by Django 2.2.6 on 2019-11-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20191030_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imovel',
        ),
    ]
