# Generated by Django 2.2.6 on 2019-11-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_remove_cliente_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cliente'),
        ),
    ]
