# Generated by Django 2.2.6 on 2019-10-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20191008_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Tipo_Status_USuario',
            new_name='Tipo_Status_Usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Login_Usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nome_Usuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Senha_Usuario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
